package Entitys;
// Generated 05/09/2017 21:55:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name = "contato",
         schema = "public"
)
public class Contato implements java.io.Serializable {

    private int codigo;
    private String contato;
    private String descricao;

    public Contato() {
    }

    public Contato(int codigo) {
        this.codigo = codigo;
    }

    public Contato(int codigo, String contato, String descricao) {
        this.codigo = codigo;
        this.contato = contato;
        this.descricao = descricao;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "contato", length = 75)
    public String getContato() {
        return this.contato;
    }

    public void setContato(String contato) {
        this.contato = contato;
    }

    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
