package entitys;
// Generated 19/08/2017 10:43:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logradouro generated by hbm2java
 */
@Entity
@Table(name="logradouro"
    ,schema="public"
)
public class Logradouro  implements java.io.Serializable {


     private int idlogradouro;
     private String nome;
     private String sigla;
     private Set enderecos = new HashSet(0);

    public Logradouro() {
    }

	
    public Logradouro(int idlogradouro) {
        this.idlogradouro = idlogradouro;
    }
    public Logradouro(int idlogradouro, String nome, String sigla, Set enderecos) {
       this.idlogradouro = idlogradouro;
       this.nome = nome;
       this.sigla = sigla;
       this.enderecos = enderecos;
    }
   
     @Id 

    
    @Column(name="idlogradouro", unique=true, nullable=false)
    public int getIdlogradouro() {
        return this.idlogradouro;
    }
    
    public void setIdlogradouro(int idlogradouro) {
        this.idlogradouro = idlogradouro;
    }

    
    @Column(name="nome", length=75)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", length=5)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logradouro")
    public Set<Endereco> getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


