package entitys;
// Generated 19/08/2017 10:43:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="public"
)
public class Pais  implements java.io.Serializable {


     private int idpais;
     private String nome;
     private String sigla;
     private Set estados = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int idpais) {
        this.idpais = idpais;
    }
    public Pais(int idpais, String nome, String sigla, Set estados) {
       this.idpais = idpais;
       this.nome = nome;
       this.sigla = sigla;
       this.estados = estados;
    }
   
     @Id 

    
    @Column(name="idpais", unique=true, nullable=false)
    public int getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(int idpais) {
        this.idpais = idpais;
    }

    
    @Column(name="nome", length=75)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", length=3)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }




}


