package Entitys;
// Generated 11/09/2017 17:34:30 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PossuiEndereco generated by hbm2java
 */
@Entity
@Table(name = "possui_endereco",
        schema = "public"
)
public class PossuiEndereco implements java.io.Serializable {

    private PossuiEnderecoId id;
    private Endereco endereco;
    private Pessoa pessoa;
    private TipoEndereco1 tipoEndereco;

    public PossuiEndereco() {
    }

    public PossuiEndereco(PossuiEnderecoId id, Endereco endereco, Pessoa pessoa, TipoEndereco1 tipoEndereco) {
        this.id = id;
        this.endereco = endereco;
        this.pessoa = pessoa;
        this.tipoEndereco = tipoEndereco;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "cliente", column = @Column(name = "cliente", nullable = false))
        , 
        @AttributeOverride(name = "endereco", column = @Column(name = "endereco", nullable = false))})
    public PossuiEnderecoId getId() {
        return this.id;
    }

    public void setId(PossuiEnderecoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endereco", nullable = false, insertable = false, updatable = false)
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cliente", nullable = false, insertable = false, updatable = false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipoendereco", nullable = false)
    public TipoEndereco1 getTipoEndereco() {
        return this.tipoEndereco;
    }

    public void setTipoEndereco(TipoEndereco1 tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
    }

}
