package Entitys;
// Generated 05/09/2017 21:55:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PossuiId generated by hbm2java
 */
@Embeddable
public class PossuiId implements java.io.Serializable {

    private int idcliente;
    private int idendereco;

    public PossuiId() {
    }

    public PossuiId(int idcliente, int idendereco) {
        this.idcliente = idcliente;
        this.idendereco = idendereco;
    }

    @Column(name = "idcliente", nullable = false)
    public int getIdcliente() {
        return this.idcliente;
    }

    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    @Column(name = "idendereco", nullable = false)
    public int getIdendereco() {
        return this.idendereco;
    }

    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PossuiId)) {
            return false;
        }
        PossuiId castOther = (PossuiId) other;

        return (this.getIdcliente() == castOther.getIdcliente())
                && (this.getIdendereco() == castOther.getIdendereco());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdcliente();
        result = 37 * result + this.getIdendereco();
        return result;
    }

}
