package Entitys;
// Generated 19/08/2017 10:43:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoendereco generated by hbm2java
 */
@Entity
@Table(name="tipoendereco"
    ,schema="public"
)
public class Tipoendereco  implements java.io.Serializable {


     private int idtipoendereco;
     private String nome;
     private String sigla;
     private String descricao;

    public Tipoendereco() {
    }

	
    public Tipoendereco(int idtipoendereco) {
        this.idtipoendereco = idtipoendereco;
    }
    public Tipoendereco(int idtipoendereco, String nome, String sigla, String descricao) {
       this.idtipoendereco = idtipoendereco;
       this.nome = nome;
       this.sigla = sigla;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="idtipoendereco", unique=true, nullable=false)
    public int getIdtipoendereco() {
        return this.idtipoendereco;
    }
    
    public void setIdtipoendereco(int idtipoendereco) {
        this.idtipoendereco = idtipoendereco;
    }

    
    @Column(name="nome", length=75)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", length=5)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    
    @Column(name="descricao", length=150)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


