package Entitys;
// Generated 05/09/2017 21:55:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipocontato generated by hbm2java
 */
@Entity
@Table(name = "tipocontato",
         schema = "public"
)
public class Tipocontato implements java.io.Serializable {

    private int codigo;
    private String nome;
    private String sigla;
    private String descricao;

    public Tipocontato() {
    }

    public Tipocontato(int codigo) {
        this.codigo = codigo;
    }

    public Tipocontato(int codigo, String nome, String sigla, String descricao) {
        this.codigo = codigo;
        this.nome = nome;
        this.sigla = sigla;
        this.descricao = descricao;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nome", length = 75)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "sigla", length = 3)
    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
