package entitys;
// Generated 22/08/2017 19:30:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipoevento generated by hbm2java
 */
@Entity
@Table(name="tipoevento"
    ,schema="public"
)
public class Tipoevento  implements java.io.Serializable {


     private int idtipoevento;
     private String nome;
     private String descricao;

    public Tipoevento() {
    }

	
    public Tipoevento(int idtipoevento) {
        this.idtipoevento = idtipoevento;
    }
    public Tipoevento(int idtipoevento, String nome, String descricao) {
       this.idtipoevento = idtipoevento;
       this.nome = nome;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="idtipoevento", unique=true, nullable=false)
    public int getIdtipoevento() {
        return this.idtipoevento;
    }
    
    public void setIdtipoevento(int idtipoevento) {
        this.idtipoevento = idtipoevento;
    }

    
    @Column(name="nome", length=75)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", length=150)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


