package Entitys;
// Generated 05/09/2017 21:55:14 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoendereco generated by hbm2java
 */
@Entity
@Table(name = "tipoendereco",
         schema = "public"
)
public class Tipoendereco implements java.io.Serializable {

    private int codigo;
    private String nome;
    private String sigla;
    private String descricao;
    private Set<Possui> possuis = new HashSet<Possui>(0);

    public Tipoendereco() {
    }

    public Tipoendereco(int codigo) {
        this.codigo = codigo;
    }

    public Tipoendereco(int codigo, String nome, String sigla, String descricao, Set<Possui> possuis) {
        this.codigo = codigo;
        this.nome = nome;
        this.sigla = sigla;
        this.descricao = descricao;
        this.possuis = possuis;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nome", length = 75)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "sigla", length = 5)
    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoendereco")
    public Set<Possui> getPossuis() {
        return this.possuis;
    }

    public void setPossuis(Set<Possui> possuis) {
        this.possuis = possuis;
    }

}
